### ISSUE TITLE
I installed this on a cloud server.   I can reach everything (gafana etc) except Guacamole

### ISSUE THREAD

**Issue by bmullan** [t13a/guacamole-hands-on#1]
see title

**Comment by t13a** [comment]
Thanks for trying it out.

I just found the problem too and have uploaded a fix (there was an error in the quoting). Could you please try it out? I'll be happy if it works.

**Comment by t13a** [comment]
P.S.

Delete the `postgres_data` volume before starting up the containers.

If you don't mind losing the data, it's easy to run `docker-compose down -v`.

**Comment by bmullan** [comment]
how do I delete the postgres_data volume

**Comment by bmullan** [comment]
Okay I think I did all of the above correctly but when I try to access guacamole on my cloud server
now I just get a totally blank white screen?

ie no Guacamole login screen

**Comment by bmullan** [comment]
@t13a 
So I retried this several times and each time I get a white blank screen where I'd expect to see the Guacamole Login screen

**Comment by bmullan** [comment]
When I browse to

https://X.X.X.X:5670/guacamole/
I get

> Error
> 
> An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs.

But _**I can successfully get the other services**_:  grafana, prometheus etc.

Only Guacamole does not work.

**Comment by bmullan** [comment]
@t13a 

here is some more data

guacamole_1      | 19:10:28.069 [http-nio-8080-exec-7] WARN  o.a.g.e.AuthenticationProviderFacade - The "postgresql" authentication provider has encountered an internal error which will halt the authentication process. If this is unexpected or you are the developer of this authentication provider, you may wish to enable debug-level logging. If this is expected and you wish to ignore such failures in the future, please set "skip-if-unavailable: postgresql" within your guacamole.properties.
guacamole_1      | 19:10:28.069 [http-nio-8080-exec-7] ERROR o.a.g.rest.RESTExceptionMapper - Unexpected internal error: 
guacamole_1      | ### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "guacamole_user" does not exist
guacamole_1      |   Position: 543
guacamole_1      | ### The error may exist in org/apache/guacamole/auth/jdbc/user/UserMapper.xml
guacamole_1      | ### The error may involve defaultParameterMap
guacamole_1      | ### The error occurred while setting parameters
guacamole_1      | ### SQL: SELECT             guacamole_user.user_id,             guacamole_entity.entity_id,             guacamole_entity.name,             password_hash,             password_salt,             password_date,             disabled,             expired,             access_window_start,             access_window_end,             valid_from,             valid_until,             timezone,             full_name,             email_address,             organization,             organizational_role,             MAX(start_date) AS last_active         FROM guacamole_user         JOIN guacamole_entity ON guacamole_user.entity_id = guacamole_entity.entity_id         LEFT JOIN guacamole_user_history ON guacamole_user_history.user_id = guacamole_user.user_id         WHERE             guacamole_entity.name = ?             AND guacamole_entity.type = 'USER'::guacamole_entity_type         GROUP BY guacamole_user.user_id, guacamole_entity.entity_id;          SELECT             guacamole_user_attribute.user_id,             guacamole_user_attribute.attribute_name,             guacamole_user_attribute.attribute_value         FROM guacamole_user_attribute         JOIN guacamole_user ON guacamole_user.user_id = guacamole_user_attribute.user_id         JOIN guacamole_entity ON guacamole_user.entity_id = guacamole_entity.entity_id         WHERE             guacamole_entity.name = ?             AND guacamole_entity.type = 'USER'::guacamole_entity_type
guacamole_1      | ### Cause: org.postgresql.util.PSQLException: ERROR: relation "guacamole_user" does not exist
guacamole_1      |   Position: 543

**Comment by t13a** [comment]
@bmullan 
Thank you for the detailed report.

That's the same problem I've encountered. The cause is that PostgreSQL is failing to initialize. To elaborate, **the PostgreSQL container run the initialization script only on the first startup**. However, if you fail to pass the initialization script, an empty DB will be created, leading to the error like you reported.

Okay. I'll describe the procedure step by step.

First, take down all the containers and delete the volumes.

```
$ docker-compose down -v
```

To be safe, discard any changes made in the local repository and pull the Git repository.

```
$ git reset --hard
$ git clean -fd
$ git pull
```

Generate a self-signed certificate (several files will be created under the `cfssl-cert` directory).

```
$ docker-compose -f docker-compose.init.yml run --rm cfssl
```

**Generate the initialization script for the PostgreSQL database**. This will create `initdb.sql` file in the `postgres_initdb` volume (the file will not be shown in this directory, it will be created in Docker volume, so we can see it in `/var/lib/docker/volumes/guacamole-hands-on_postgres_initdb/_data`).

```
$ docker-compose -f docker-compose.init.yml run --rm guacamole
```

Last, start up the containers. Check the logs of the `postgres` container and make sure that the database schema has been created (you should see continuous output such as `CREATE TABLE`).

```
$ docker-compose up -d
$ docker-compose logs -f postgres
```

I would appreciate it if you could let me know the results.

**Comment by bmullan** [comment]
I followed your instructions except i just downloaded the repo .ZIP file to my cloud server then unzipped it.

PostgreSQL looks ok:

> 
> **$  docker-compose -f docker-compose.init.yml run --rm cfssl**
> Creating network "guacamole-hands-on-master_default" with the default driver
> Creating volume "guacamole-hands-on-master_postgres_initdb" with default driver
> Creating guacamole-hands-on-master_cfssl_run ... done
> + cfssl gencert -initca ca-csr.json
> + cfssljson -bare ca
> 2021/08/18 23:11:00 [INFO] generating a new CA key and certificate from CSR
> 2021/08/18 23:11:00 [INFO] generate received request
> 2021/08/18 23:11:00 [INFO] received CSR
> 2021/08/18 23:11:00 [INFO] generating key: ecdsa-256
> 2021/08/18 23:11:00 [INFO] encoded CSR
> 2021/08/18 23:11:00 [INFO] signed certificate with serial number 270571826825465928662857196679642506933539685079
> + cfssljson -bare server
> + cfssl gencert -ca=ca.pem -ca-key=ca-key.pem --config=ca-config.json -profile=server server-csr.json
> 2021/08/18 23:11:00 [INFO] generate received request
> 2021/08/18 23:11:00 [INFO] received CSR
> 2021/08/18 23:11:00 [INFO] generating key: rsa-2048
> 2021/08/18 23:11:00 [INFO] encoded CSR
> 2021/08/18 23:11:00 [INFO] signed certificate with serial number 455985360150450116422348953118441621328598569150
> bmullan@ciab:/opt/ciab/guacamole-hands-on-master$ docker-compose -f docker-compose.init.yml run --rm guacamole
> Creating guacamole-hands-on-master_guacamole_run ... done
> + /opt/guacamole/bin/initdb.sh --postgres
> bmullan@ciab:/opt/ciab/guacamole-hands-on-master$ docker-compose up -d
> Creating volume "guacamole-hands-on-master_grafana_data" with default driver
> Creating volume "guacamole-hands-on-master_grafana_log" with default driver
> Creating volume "guacamole-hands-on-master_guacamole_conf" with default driver
> Creating volume "guacamole-hands-on-master_postgres_data" with default driver
> Creating volume "guacamole-hands-on-master_prometheus_data" with default driver
> Creating node_exporter                        ... done
> Creating cadvisor                             ... done
> Creating guacamole-hands-on-master_postgres_1   ... done
> Creating guacamole-hands-on-master_guacd_1      ... done
> Creating guacamole-hands-on-master_prometheus_1 ... done
> Creating guacamole-hands-on-master_adminer_1    ... done
> Creating guacamole-hands-on-master_guacamole_1  ... done
> Creating guacamole-hands-on-master_grafana_1    ... done
> Creating guacamole-hands-on-master_nginx_1      ... done
> bmullan@ciab:/opt/ciab/guacamole-hands-on-master$ docker-compose logs -f postgres
> Attaching to guacamole-hands-on-master_postgres_1
> postgres_1       | The files belonging to this database system will be owned by user "postgres".
> postgres_1       | This user must also own the server process.
> postgres_1       | 
> postgres_1       | The database cluster will be initialized with locale "en_US.utf8".
> postgres_1       | The default database encoding has accordingly been set to "UTF8".
> postgres_1       | The default text search configuration will be set to "english".
> postgres_1       | 
> postgres_1       | Data page checksums are disabled.
> postgres_1       | 
> postgres_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
> postgres_1       | creating subdirectories ... ok
> postgres_1       | selecting dynamic shared memory implementation ... posix
> postgres_1       | selecting default max_connections ... 100
> postgres_1       | selecting default shared_buffers ... 128MB
> postgres_1       | selecting default time zone ... Etc/UTC
> postgres_1       | creating configuration files ... ok
> postgres_1       | running bootstrap script ... ok
> postgres_1       | performing post-bootstrap initialization ... ok
> postgres_1       | syncing data to disk ... ok
> postgres_1       | 
> postgres_1       | initdb: warning: enabling "trust" authentication for local connections
> postgres_1       | You can change this by editing pg_hba.conf or using the option -A, or
> postgres_1       | --auth-local and --auth-host, the next time you run initdb.
> postgres_1       | 
> postgres_1       | Success. You can now start the database server using:
> postgres_1       | 
> postgres_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
> postgres_1       | 
> postgres_1       | waiting for server to start....2021-08-18 23:11:33.678 UTC [34] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
> postgres_1       | 2021-08-18 23:11:33.680 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> postgres_1       | 2021-08-18 23:11:33.686 UTC [35] LOG:  database system was shut down at 2021-08-18 23:11:33 UTC
> postgres_1       | 2021-08-18 23:11:33.691 UTC [34] LOG:  database system is ready to accept connections
> postgres_1       |  done
> postgres_1       | server started
> postgres_1       | CREATE DATABASE
> postgres_1       | 
> postgres_1       | 
> postgres_1       | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/initdb.sql
> postgres_1       | CREATE TYPE
> postgres_1       | CREATE TYPE
> postgres_1       | CREATE TYPE
> postgres_1       | CREATE TYPE
> postgres_1       | CREATE TYPE
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE INDEX
> postgres_1       | CREATE TABLE
> postgres_1       | CREATE INDEX
> postgres_1       | INSERT 0 1
> postgres_1       | INSERT 0 1
> postgres_1       | INSERT 0 6
> postgres_1       | INSERT 0 3
> postgres_1       | 
> postgres_1       | 
> postgres_1       | 2021-08-18 23:11:34.566 UTC [34] LOG:  received fast shutdown request
> postgres_1       | waiting for server to shut down....2021-08-18 23:11:34.567 UTC [34] LOG:  aborting any active transactions
> postgres_1       | 2021-08-18 23:11:34.571 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
> postgres_1       | 2021-08-18 23:11:34.573 UTC [36] LOG:  shutting down
> postgres_1       | 2021-08-18 23:11:34.614 UTC [34] LOG:  database system is shut down
> postgres_1       |  done
> postgres_1       | server stopped
> postgres_1       | 
> postgres_1       | PostgreSQL init process complete; ready for start up.
> postgres_1       | 
> postgres_1       | 2021-08-18 23:11:34.700 UTC [1] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
> postgres_1       | 2021-08-18 23:11:34.702 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> postgres_1       | 2021-08-18 23:11:34.707 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> postgres_1       | 2021-08-18 23:11:34.712 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> postgres_1       | 2021-08-18 23:11:34.726 UTC [72] LOG:  database system was shut down at 2021-08-18 23:11:34 UTC
> postgres_1       | 2021-08-18 23:11:34.733 UTC [1] LOG:  database system is ready to accept connections
> 

I point my browser to my cloud server:

> **https://178.X.X.X:5670/guacamole/**  

_and I get a Blank White screen instead of the Guacamole Login screen._

NOTE:   gotta ask the stupid question
In your README all the examples URLs are

    https://localhost:5670/: Apache Guacamole (redirection)
    https://localhost:5670/adminer/: Adminer
    https://localhost:5670/cadvisor/: cAdvisor
    https://localhost:5670/grafana/: Grafana
    https://localhost:5670/guacamole/: Apache Guacamole
    https://localhost:5670/node-exporter/: Node Exporter
    https://localhost:5670/prometheus/: Prometheus

If the host is remote there is no reason not to substitute the remote server's IP address for "localhost" in the above.

Like I said it seems to work for all of the services BUT Guacamole

**Comment by t13a** [comment]
@bmullan 
Thank you for your report. We have solved the first problem, but now there seems to be another problem.

Sorry, but I have to work now, so I will reply a little later.

**Comment by t13a** [comment]
@bmullan 
Of course, when accessing from a remote location, it is correct to replace `localhost` with your IP address. I can access Guacamole both locally and remotely.

One of the major reasons why you can't access Guacamole is lack of resources on your computer. Guacamole consumes a lot of memory (more than 500 MB), so it may have failed to start on a small virtual machine.

Please make sure that the `guacamole` container is displayed as `Up` state with the following command.

```
$ docker-compose ps
```

If the Guacamole process is not running (it should have been restarted repeatedly), the reverse proxy will return a white blank screen (I tried stopping Guacamole in my environment, and the same phenomenon was reproduced).

**Comment by bmullan** [comment]
The server I am installing/running this on is a Digital Ocean (cloud)
server:

*resources: * 8 GB Memory / 4 AMD vCPUs / 160 GB Disk / NYC1 - Ubuntu 20.04
(LTS) x64

**Comment by bmullan** [comment]
You said...

> One of the major reasons why you can't access Guacamole is lack of resources on your computer. Guacamole consumes a lot of memory (more than 500 MB), so it may have failed to start on a small virtual machine.

The Cloud server has:
 **8 GB Memory / 4 AMD vCPUs / 160 GB SSD Disk - Ubuntu 20.04 (LTS) x64**

So it was **not** a memory etc resource problem.

**Comment by t13a** [comment]
I don't have time to talk any more, so our conversation is over.
